version: "3"

volumes:
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres:11.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data_elixir1
    ports:
      - "5432:5432"