name: Elixir CI
env:
  MIX_ENV: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2

    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.2 # Define the elixir version [required]
        otp-version: 22.0 # Define the OTP version [required]

    - name: Install Dependencies
      run: mix deps.get

    - name: Run Credo
      run: mix credo

    - name: Run Tests
      run: mix test

    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}